version: "3"

services:
  web:
    container_name: campo-minado-web
    build: .
    environment:
      DB_SERVER: campo-minado-db
      DB_NAME: campo_minado
      DB_USER: user
      DB_PASS: user_pass
    ports:
      - 8008:8000
    volumes:
      - .:/var/app
  db:
    container_name: campo-minado-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: campo_minado
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pass
    ports:
      - 3309:3306
    volumes:
      - ./data:/var/lib/mysql
